services:
  db:
    build: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  sftp:
    image: atmoz/sftp
    command: sftp_user:sftp_password:::backup

  backup:
    image: idgis/postgresql-backup
    restart: always
    environment:
      # format: $DB_HOST:$DB_PORT:$DB_NAME:$DB_USER:$DB_PASSWORD:$POSTGRESQL_VERSION
      - DATABASE_0=db:5432:db_0:postgres:postgres:13
      - DATABASE_1=db:5432:db_1:postgres:postgres:13
      - SFTP_USER=sftp_user
      - SFTP_PASSWORD=sftp_password
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - BACKUP_NAME=backup/db
      - PASSPHRASE=passphrase
